#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $ac_adapt;
my $full_text;
my $short_text;
my $bat_number = $ENV{BAT_NUMBER} || 0;
my $label = $ENV{LABEL} || "";

# read the first line of the "acpi" command output
open (ACPI, "acpi -b 2>/dev/null| grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if (not defined($acpi)) {
    # don't print anything to stderr if there is no battery
    exit(0);
}
elsif ($acpi !~ /: ([\w\s]+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$label$percent%";

if ($status eq 'Discharging') {
	$full_text .= ' 󰁹'; #symbol for discharging
} elsif ($status eq 'Charging') {
	$full_text .= ' 󰂄'; #symbol for charging
} elsif ($status eq 'Unknown') {
	open (AC_ADAPTER, "acpi -a |") or die;
	$ac_adapt = <AC_ADAPTER>;
	close(AC_ADAPTER);

	if ($ac_adapt =~ /: ([\w-]+)/) {
		$ac_adapt = $1;

		if ($ac_adapt eq 'on-line') {  #on line
			$full_text .= ' +';   #chr
		} elsif ($ac_adapt eq 'off-line') {  #off line
			$full_text .= ' -';  #DIS
		}
	}
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#f41e0a\n";
	} elsif ($percent < 30) {
		print "#e2c81e\n";
	} elsif ($percent < 60) {
		print "#b8b8b8\n";
	} elsif ($percent < 85) {
		print "#b8b8b8\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
