#!/bin/bash

RED=$(tput setaf 1)
NC=$(tput sgr0)
device=${BLOCK_INSTANCE:-/dev/video0} 
if [[ -c "${device}" ]]; then   
 if [[ "$(fuser /dev/video0)" != "" ]]; then     
  echo " "     
  echo " "     
  echo ""   
 else     
  echo " "     
  echo " "     
  echo ""   
 fi 
fi
