#!/usr/bin/env bash

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi
#------------------------------------------------------------------------

COLOR_GE80=${COLOR_GE80:-#C4CBD4} #00ff00
COLOR_GE60=${COLOR_GE60:-#C4CBD4} #fff600
COLOR_GE40=${COLOR_GE40:-#e2c81e} #ffae00
COLOR_LOWR=${COLOR_LOWR:-#e2c81e} 
COLOR_DOWN=${COLOR_DOWN:-#c4cbd4}

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "󰌙"
    echo "󰌙"
    echo $COLOR_DOWN
    exit
fi

#------------------------------------------------------------------------

QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

#------------------------------------------------------------------------

echo $QUALITY% # full text
echo $QUALITY% # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    echo $COLOR_GE40
else
    echo $COLOR_LOWR
fi
